archives:
  - format_overrides:
    - goos: windows
      format: zip
  - files:
    - README.md
    - LICENSE
    - CHANGELOG
    - phishlets/*

builds:
  - id: "evilginx2"
    goos:
    - windows
    - linux
    - darwin
    goarch:
    - 386
    - amd64
    - arm
    - arm64
    ignore:
    - goos: darwin
      goarch: 386
    - goos: darwin
      goarch: arm
    - goos: windows
      goarch: arm
    - goos: windows
      goarch: arm64